<?php

namespace Database\Seeders;

use App\Models\PlunrSetting;
use Illuminate\Database\Seeder;

/**
 * Applies sidebar logo URLs committed under public/branding/.
 * Generated by PLUNR Studio. Re-run after merging branding PRs:
 *   php artisan db:seed --class=PlunrSidebarBrandingSeeder
 */
class PlunrSidebarBrandingSeeder extends Seeder
{
    public function run(): void
    {
        $logos = array (
  'sidebar_logo_light_url' => NULL,
  'sidebar_logo_dark_url' => '/branding/sidebar-logo-dark.png',
  'sidebar_logo_collapsed_url' => NULL,
);

        $current = PlunrSetting::valueFor('account');

        foreach ($logos as $key => $url) {
            if ($url === null) {
                unset($current[$key]);
            } else {
                $current[$key] = $url;
            }
        }

        PlunrSetting::putValue('account', $current);
    }
}
